### ISSUE TITLE
Err 500 sur les tags

### ISSUE THREAD

**Issue by victorweiss** [victorweiss/elsass-web-devs#39]
https://www.elsass-web-devs.fr/blog/tag/elsasswebdevs
 
<img width="1522" alt="Capture d’écran 2023-02-01 à 23 16 21" src="https://user-images.githubusercontent.com/43701520/216176125-c83bbe20-2e1b-4eec-86bc-756d7b4ebadf.png">

**Comment by Trait2Jauge** [comment]
Corrigé
https://github.com/victorweiss/elsass-web-devs/pull/40

**Comment by victorweiss** [comment]
Nickel 👍 
Parfait la création de la branche pour régler l'issue. Mais encore plus pratique si tu créer la branche à partir du menu de droite ici sur l'issue, ça va automatiquement lier la Pull Request à l'issue, et automatiquement fermer l'issue quand on merge la PR
